# Generated by Django 5.0.1 on 2024-01-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retia_api', '0014_detector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('messages', models.CharField(blank=True, max_length=255)),
                ('time', models.DateTimeField(null=True)),
                ('user', models.CharField(default='Anonymous', max_length=200)),
            ],
        ),
    ]
