# Generated by Django 5.0.1 on 2024-02-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retia_api', '0018_delete_log_alter_detector_filebeat_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detector',
            name='elastic_host',
            field=models.CharField(max_length=200),
        ),
    ]
