# Generated by Django 5.0.1 on 2024-02-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retia_api', '0019_alter_detector_elastic_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detector',
            name='elastic_host',
        ),
        migrations.AlterField(
            model_name='detector',
            name='filebeat_port',
            field=models.IntegerField(default=50255),
        ),
        migrations.AlterField(
            model_name='device',
            name='mgmt_ipaddr',
            field=models.GenericIPAddressField(),
        ),
    ]
