# Generated by Django 5.0.1 on 2024-02-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retia_api', '0021_detector_elastic_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
                ('severity', models.CharField(blank=True, max_length=255)),
                ('instance', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=10)),
                ('messages', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
