# Generated by Django 5.0.1 on 2024-01-09 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retia_api', '0003_alter_device_ipaddr'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='device',
            name='modified_at',
            field=models.DateField(auto_now=True),
        ),
    ]
