# Generated by Django 5.0.1 on 2024-01-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retia_api', '0011_device_secret_device_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='port',
            field=models.IntegerField(default=443, max_length=5),
        ),
    ]
