# Generated by Django 5.0.1 on 2024-01-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retia_api', '0012_device_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='port',
            field=models.IntegerField(default=443),
        ),
    ]
