# Generated by Django 5.0.1 on 2024-01-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retia_api', '0015_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detector',
            name='device_interface',
        ),
        migrations.AddField(
            model_name='detector',
            name='device_interface_to_filebeat',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='detector',
            name='device_interface_to_server',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
