# Generated by Django 5.0.1 on 2024-01-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retia_api', '0017_alter_device_secret_alter_device_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.AlterField(
            model_name='detector',
            name='filebeat_port',
            field=models.BigIntegerField(default=50255),
        ),
        migrations.AlterField(
            model_name='detector',
            name='sampling_interval',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='detector',
            name='window_size',
            field=models.IntegerField(default=1),
        ),
    ]
