# Generated by Django 5.0.1 on 2024-01-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retia_api', '0002_rename_devices_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ipaddr',
            field=models.CharField(max_length=15),
        ),
    ]
